export enum ProcessStatusEnum {
  INCOMPLETE = 'INCOMPLETO',
  COMPLETE = 'COMPLETO',
  EN_PROCESO = 'EN_PROCESO',
  CORRECTED = 'CORREGIDO',
  UNDER_OBSERVATION = 'OBSERVADO',
  VERIFIED = 'VERIFICADO',
  APPOINTMENT_SCHEDULED = 'CITA_PROGRAMADA',
}
